# Generated by Django 5.2 on 2025-10-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('EVALUATING', 'Evaluating'), ('EVALUATED', 'Evaluated')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submissions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sumbissions', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('PASSED', 'Passed'), ('RUN_ERR', 'Runtime error'), ('COMP_ERR', 'Compilation error'), ('TIMEOUT', 'Timeout'), ('INT_SERV_ERR', 'Internal server error')])),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='submissions.submission')),
            ],
        ),
    ]
